version: '3'

services:
  postgres:
    build:
      context: ../databasepsql
    ports:
      - "5432:5432"
    networks:
      - todonetwork

  backend:
    build:
      context: ../backend
    ports:
      - "9988:9988"
    networks:
      - todonetwork
    depends_on:
      - postgres

  frontend:
    build:
      context: ../distributedsystemsproject
    ports:
      - "80:80"
    networks:
      - todonetwork
    depends_on:
      - backend

networks:
  todonetwork:
    driver: bridge